

name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps: 
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            scratchattach:
              - 'scratchattach/**'
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - if: steps.changes.outputs.scratchattach == 'true'
        name: did anything change
        run: |
          echo things have changed
